# Generated by Django 3.0.7 on 2020-07-07 03:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signifier', models.CharField(choices=[('*', 'Priority'), ('!', 'Inspiration'), (' ', 'None')], default=' ', max_length=4)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signifier', models.CharField(choices=[('*', 'Priority'), ('!', 'Inspiration'), (' ', 'None')], default=' ', max_length=4)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signifier', models.CharField(choices=[('*', 'Priority'), ('!', 'Inspiration'), (' ', 'None')], default=' ', max_length=4)),
                ('status', models.CharField(choices=[('.', 'Incomplete'), ('x', 'Complete')], default='.', max_length=4)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
