# Generated by Django 3.0.7 on 2020-06-23 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signifier', models.CharField(choices=[('*', 'Priority'), ('!', 'Inspiration'), ('', 'None')], default='', max_length=4)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_bullets.bullet_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('bullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bullets.Bullet')),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bullets.bullet',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('bullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bullets.Bullet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bullets.bullet',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('bullet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bullets.Bullet')),
                ('status', models.CharField(choices=[('.', 'Incomplete'), ('x', 'Complete')], default='.', max_length=4)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bullets.bullet',),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullets.Bullet')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='bullets.List')),
            ],
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'index'], name='bullets_lis_list_id_2a78ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('list', 'index')},
        ),
    ]
