# Generated by Django 3.0.7 on 2020-06-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='signifier',
            field=models.CharField(choices=[('*', 'Priority'), ('!', 'Inspiration'), (' ', 'None')], default=' ', max_length=4),
        ),
    ]
