# Generated by Django 3.0.7 on 2020-06-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0002_auto_20200629_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
